### ISSUE TITLE
cFileConfigReader : cant find input file

### ISSUE THREAD

**Issue by krishna51119** [audeering/opensmile#10]
I am trying to use opensmile 3.0 in python in windows 10. Downloaded from official website. Extract the folder. In cmd change working directory to opensmile\bin\SMILExtract -h
then it says installation is done as I can see the version and other details.

Finally for feature extraction

C:\Users\HP\Desktop\opensmile\bin>SMILExtract -C config\mfcc\MFCC12_0_D_A.conf -I Desktop\s.wav -O K.csv
(MSG) [2] SMILExtract: openSMILE starting!
(MSG) [2] SMILExtract: config file is: config\mfcc\MFCC12_0_D_A.conf
(MSG) [2] cComponentManager: successfully registered 103 component types.
(ERR) [1] configManager: cFileConfigReader::openInput : cannot find input file 'config\mfcc\MFCC12_0_D_A.conf'!

Please guide

**Comment by krishna51119** [comment]
I tried it in python code too, as given 

exe_opensmile = "C:/Users/HP/Desktop/opensmile/bin/SMILExtract"
path_config   = "C:/Users/HP/Desktop/opensmile/config/mfcc/MFCC12_0_D_A.conf"
outfilename = './IEMOCAP.csv'
opensmile_call = exe_opensmile + " -C " + path_config + " -I " + infilename + " -O " +  outfilename
                         
Fortunately its creating csv file in same folder named IEMOCAP but its not readable. Few initial lines are

Á† œ	ÀÃ}rÁ`eÌ@×oGÁË¹ô@ÄîÁ©@ówÁ¯"ÀàV@GAuïó@ë’BÎÆÒ?i»¿‰<   ?×z?‘E=¿ŽŽÌ¿Ä¦s¾´j@-8A@5w¾øºšÀæåÀe¾¼Í=ãÆƒ>ì | j¾Ûæý>’Ðã>Ý`š?9Vµ?b˜=ÿz>8º=¿ |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
\|"¾ƒ¡è>Ü¤k¾«ARÀm’ÙÁžoºA!žpÁ­µªÀ#²ÁÉ¡›= |   |   |   |   |   |   |   |  
4®Á¼×»?îL§@=júAFV+Á\|\BÎw?¢°Ž¾x+¦?…P¢?úqÀ¿@ß¿‘«@òú@´Ò@‘¥-¿\ùÀd?­Àžâ¿™À=\|2¾?/§I¿5¥R>¼3–?[ö¦?°­ˆ?„’E¿D{ž¿8ok¿–ét¼

Tried all encoding for csv reader but nothing is working.  Strange but no online resources or forum I can find for my answers. :(

**Comment by chausner-audeering** [comment]
In your first example, the path to the config file is wrong, you are missing a `..\`. Also the relative path to your input wave file seems wrong, you'll probably want to use absolute paths:
```
SMILExtract -C ..\config\mfcc\MFCC12_0_D_A.conf -I C:/Users/HP/Desktop/s.wav -O K.csv
```

The problem with the CSV contents is because you are using the `-O` option which outputs in HTK format. You will want to use `-csvoutput`:
```
SMILExtract -C ..\config\mfcc\MFCC12_0_D_A.conf -I C:/Users/HP/Desktop/s.wav -csvoutput K.csv
```

**Comment by krishna51119** [comment]
@chausner-audeering 
Thank you so much for reply sir, Where is the output file created if executed correctly, like what will be the location of K.csv. (In case of command window feature extraction)

And sir in python code, are you saying I should write 

outfilename = 'IEMOCAP.csv'
opensmile_call = exe_opensmile + " -C " + path_config + " -I " + infilename + " -csvoutput" +  outfilename

Coz now its not even creating this file named IEMOCAP.csv

Many Thanks :)

**Comment by krishna51119** [comment]
> @chausner-audeering
> Thank you so much for reply sir, Where is the output file created if executed correctly, like what will be the location of K.csv. (In case of command window feature extraction)
> 
> And sir in python code, are you saying I should write
> 
> outfilename = 'IEMOCAP.csv'
> opensmile_call = exe_opensmile + " -C " + path_config + " -I " + infilename + " -csvoutput" + outfilename
> 
> Coz now its not even creating this file named IEMOCAP.csv
> 
> Many Thanks :)

Sir I got the first answer plz guide how to use in python coding, in second question.
I was using cmd for checking whether its working properly. Sir there its working

**Comment by chausner-audeering** [comment]
Missing space in " -csvoutput"

**Comment by krishna51119** [comment]
Its still working dont know why :)
But thank you so much 

Regards

**Comment by krishna51119** [comment]
Sir are these all config file extract the features in a similar formats?
I am getting the first column as "unknown" here for most of the config
files while extracting mfcc.(opensmile 3.0 windows)
and few are not working for csv though I am getting htk again (even I
mentioned '- csvoutput') does that mean these features are not extracted in
csv format sir?


Reagrds

**Comment by chausner-audeering** [comment]
Not all config files support all output formats. Most support CSV output using `-csvoutput` but some are hard-coded to create HTK output only, for example.

The column with "unknown" is normal, you can ignore it.
