### ISSUE TITLE
when i  build  aar  ，An error occurred

### ISSUE THREAD

**Issue by chunyaZOU** [audeering/opensmile#13]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':opensmile:swig'.
> A problem occurred starting process 'command 'sed''

**Comment by chausner-audeering** [comment]
There is a known issue with building the Android sample project on macOS. Please see https://github.com/audeering/opensmile/issues/5#issuecomment-762539050 for a workaround.

**Comment by chunyaZOU** [comment]
thank  you. it works
