### ISSUE TITLE
Error when running the build process

### ISSUE THREAD

**Issue by IcyHao** [audeering/opensmile#15]
Hi, I try to set up opensmile on my laptop and when I run the command " powershell -ExecutionPolicy Bypass -File build.ps1", I got a warning and an error. I can't figure out what goes wrong. Could you give me some help?

* I had attached the error log file
[CMakeError.log](https://github.com/audeering/opensmile/files/6415096/CMakeError.log)

**Comment by chausner-audeering** [comment]
> "D:\opensmile\build\CMakeFiles\3.20.2\CompilerIdC\CompilerIdC.vcxproj" (default target) (1) ->
(PrepareForBuild target) -> 
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(473,5): warning MSB8003: The WindowsSDKDir property is not defined. Some build tools may not be found. [D:\opensmile\build\CMakeFiles\3.20.2\CompilerIdC\CompilerIdC.vcxproj]

It seems something is wrong with your Visual Studio installation. Make sure you have Visual Studio C++ installed with all default components.

**Comment by IcyHao** [comment]
Ok, I got it. When I try to run the "SMILExtract -h" command, it says it is not recognized but I had already added the build/progsrc/smilextract to the path. Is there any further step I need to do?

**Comment by chausner-audeering** [comment]
On Windows, make sure to close and reopen any command-prompts after changing the PATH. No further steps are necessary. If it still does not work, something is wrong in how you added the build folder to the PATH.

**Comment by chausner-audeering** [comment]
I'll close this issue due to inactivity.
