### ISSUE TITLE
Error when running build process on Linux

### ISSUE THREAD

**Issue by ShamilaNasreen** [audeering/opensmile#18]
Hi, I try to set up open smile 3.0 on Linux and when I run the command " sh build. sh", I got an error. I can't figure out what goes wrong. Could you give me some help? I have cmake version 3.20.2 and gcc version 4.8.5 20150623 (Red Hat 4.8.5-39)
I had attached the error log file:
[CMakeError.log](https://github.com/audeering/opensmile/files/6539141/CMakeError.log)

**Comment by chausner-audeering** [comment]
Please try with a more recent version of gcc, it could be that it is not compatible with gcc 4.x. A C++11-compliant compiler is required.

**Comment by rbrueckner** [comment]
Confirmed: using e.g. gcc v9.3.0 does the job! So one requires a more recent version of gcc.
Thanks!
