### ISSUE TITLE
opensmile-3.0-osx-x64.tar.gz can't decompress

### ISSUE THREAD

**Issue by srdfjy** [audeering/opensmile#21]
![image](https://user-images.githubusercontent.com/66103286/126956280-491ad2e4-3253-4560-8066-58ddcc117275.png)

**Comment by xfoq** [comment]
![image](https://user-images.githubusercontent.com/66103286/126956022-e464b56d-1206-490c-b6e1-0d4f38d920cd.png)

**Comment by drux007** [comment]
Hi @xfoq,

I guess you are trying to decompress it on your OSX device, right?

**Comment by xfoq** [comment]
> Hi @xfoq,
> 
> I guess you are trying to decompress it on your OSX device, right?

yes

**Comment by chausner-audeering** [comment]
It appears the file you downloaded is corrupted/truncated. Please try downloading it again. Its size should be 14.373.112 bytes.

**Comment by xfoq** [comment]
> It appears the file you downloaded is corrupted/truncated. Please try downloading it again. Its size should be 14.373.112 bytes.

Hi @chausner-audeering,

I downloaded from the release, and there was no notification that the download failed.

![image](https://user-images.githubusercontent.com/66103286/126964652-bc590846-b323-45e7-8c67-9d721ecd1411.png)

**Comment by drux007** [comment]
I downloaded it from the [release page](https://github.com/audeering/opensmile/releases/tag/v3.0.0) and I can successfully extract both versions:
* osx
* linux

using the same command as you provided above:
```
tar zxf file.tar.gz
```
on my Linux device so it seems that something goes wrong when you download it.

**Comment by xfoq** [comment]
> I downloaded it from the [release page](https://github.com/audeering/opensmile/releases/tag/v3.0.0) and I can successfully extract both versions:
> 
> * osx
> * linux
> 
> using the same command as you provided above:
> 
> ```
> tar zxf file.tar.gz
> ```
> 
> on my Linux device so it seems that something goes wrong with your download.

thanks @drux007 ,

I compile from source code and can be used.

**Comment by drux007** [comment]
Closing issue.
