### ISSUE TITLE
中間発表質問

### ISSUE THREAD

**Issue by 478Chisa** [audeering/opensmile#24]
- メル周波数ケプストラムの平均ではなく、ある地点での結果にしかすぎないので、下の説明が不適切
- 方法の部分が小さいので、導入と背景を少なくする
    - 収録状況の担保、収録テキストの説明を細かく
- 参考文献の[1]とかを明記
- 日本人の３割が話しにくさを感じているとあるが、構音障害者に向けたシステムなのか、健常者レベルの話なのか立場をしっかりしたほうがいい
- 健常者の側音化構音チックなもので本当に結果がでるのかどうか
- 結果のグラフの意味が一眼でわかるようにしたほうがいい
- 側音化構音が何を示しているかもっとわかりやすかったらいい（初めての方にもわかりやすいように）
- 音声を保存するプログラムは用意しろと言うことで、作れと言うことではない（ここを浅井さんに確認）
- MRIの見方が初心者にはわからないのでは（３Dとかの方がいいんじゃん）
- 従来手法、トレーニングシステム手法、提示しない方法での比較が必要
- 定着までがゴールなら厳しいけど、短期的にならいけるのではないか（家帰ったらできなくなってもいいから）
- 変に教育要素はない方がいいのでは、、？研究の範囲が広すぎるのでは

**Comment by chausner-audeering** [comment]
Sorry but I think these suggestions are not related to openSMILE in any way, so I'll close this issue. If I am mistaken, please reopen.
