### ISSUE TITLE
SMILExtract -h: command not found

### ISSUE THREAD

**Issue by spagliarini** [audeering/opensmile#25]
Hi,

I am trying to set up openSMILE on my mac. I am following the instructions for LINUX/MAC (from source) on the "Get started" webpage. Everything is fine, until this point:

> This will configure and build the libopensmile library and the SMILExtract binary. After successful compilation, you may want to add the build/progsrc/smilextract directory to your path or copy the binary build/progsrc/smilextract/SMILExtract to a directory in your search path. Finally, start by running: 
> 
> SMILExtract -h
> 

I added the directory to my path but the command cannot be found. I am confused about what I can possible be doing wrong. Any idea of why? 

Or, if there is another way to set up opensmile (or directly a python library-package that I can pip install), I am all ears. 

Thank you to anyone available to give me their 2 cents!
Silvia

**Comment by chausner-audeering** [comment]
You do not necessarily need to add the SMILExtract directory to your PATH. Are you sure the build succeeded and there is a `SMILExtract` binary in `build/progsrc/smilextract`?

Instead of building openSMILE yourself, you might also want to just use the prebuilt binaries from the Releases page on GitHub.

**Comment by spagliarini** [comment]
Thank you so much for the quick reply.

> You do not necessarily need to add the SMILExtract directory to your PATH. Are you sure the build succeeded and there is a SMILExtract binary in build/progsrc/smilextract?

I can see the executable inside the directory.

> Instead of building openSMILE yourself, you might also want to just use the prebuilt binaries from the Releases page on GitHub.

I am trying this way now. I downloaded the tar file and just navigating to the directory, I still can't run SMILExtract -h (command not found). I thought I might need to do something first, and by reading the readme I see that it mentions to run bash build.sh : but there is no such directory. 
I am really sorry for all these questions, I must sound very naive here.

**Comment by chausner-audeering** [comment]
You may need to specify the current directory or full path when invoking SMILExtract in the shell: `./SMILExtract`

**Comment by spagliarini** [comment]
Ok, this worked. Thank you so much for the help.
