### ISSUE TITLE
./SMILExtract: error while loading shared libraries: libmvec.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by srdfjy** [audeering/opensmile#27]
When I execute `./SMILExtract -h` on Linux, the following error occurs. How can I solve it?

`./SMILExtract: error while loading shared libraries: libmvec.so.1: cannot open shared object file: No such file or directory`

**Comment by chausner-audeering** [comment]
This error means that a certain library was not found on your system. On which operating system and version are you trying to run openSMILE? For some systems, you can install the missing libraries as additional packages.

**Comment by srdfjy** [comment]
Hi @chausner-audeering 

CentOS Linux release 7.4.1708 (Core)

**Comment by chausner-audeering** [comment]
You may want to try installing https://centos.pkgs.org/7/ghettoforge-testing-x86_64/glibc231-2.31-3.gf.el7.x86_64.rpm.html. If that does not fix it, I suggest you compile openSMILE yourself on your system.

**Comment by srdfjy** [comment]
Hi，I got the following error while installing glibc231.

-----------------------------------------------------------------------------------

Loaded plugins: fastestmirror, langpacks, nvidia
Repository base is listed more than once in the configuration
Repository update is listed more than once in the configuration
Repository extras is listed more than once in the configuration
Repository centosplus is listed more than once in the configuration
Repository contrib is listed more than once in the configuration
Repository epel is listed more than once in the configuration
Repository dag is listed more than once in the configuration
Repository puppetlabs-products is listed more than once in the configuration
Repository puppetlabs-deps is listed more than once in the configuration
Repository puppetlabs-devel is listed more than once in the configuration
Repository puppetlabs-products-source is listed more than once in the configuration
Repository puppetlabs-deps-source is listed more than once in the configuration
Repository puppetlabs-devel-source is listed more than once in the configuration
autohome_rdop                                                                                                                                                                               | 2.9 kB  00:00:00     
open-falcon-agent                                                                                                                                                                           | 2.9 kB  00:00:00     
Loading mirror speeds from cached hostfile
Resolving Dependencies
--> Running transaction check
---> Package glibc231.x86_64 0:2.31-3.gf.el7 will be installed
--> Processing Dependency: glibc-langpack = 2.31-3.gf.el7 for package: glibc231-2.31-3.gf.el7.x86_64
--> Processing Dependency: glibc-common = 2.31-3.gf.el7 for package: glibc231-2.31-3.gf.el7.x86_64
--> Running transaction check
---> Package glibc231.x86_64 0:2.31-3.gf.el7 will be installed
--> Processing Dependency: glibc-common = 2.31-3.gf.el7 for package: glibc231-2.31-3.gf.el7.x86_64
---> Package glibc231-langpack-zu.x86_64 0:2.31-3.gf.el7 will be installed
--> Processing Dependency: glibc231-common = 2.31-3.gf.el7 for package: glibc231-langpack-zu-2.31-3.gf.el7.x86_64
--> Running transaction check
---> Package glibc231.x86_64 0:2.31-3.gf.el7 will be installed
--> Processing Dependency: glibc-common = 2.31-3.gf.el7 for package: glibc231-2.31-3.gf.el7.x86_64
---> Package glibc231-common.x86_64 0:2.31-3.gf.el7 will be installed
--> Finished Dependency Resolution
Error: Package: glibc231-2.31-3.gf.el7.x86_64 (gf-testing)
           Requires: glibc-common = 2.31-3.gf.el7
           Installed: glibc-common-2.17-196.el7.x86_64 (@anaconda)
               glibc-common = 2.17-196.el7
           Available: glibc-common-2.17-196.el7_4.2.x86_64 (contrib)
               glibc-common = 2.17-196.el7_4.2
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by srdfjy** [comment]
When I tried to compile on centos7, the following error occurred.

----------------------------------------------------------------

[ 21%] Building CXX object CMakeFiles/opensmile.dir/src/core/dataProcessor.cpp.o
/data/home/opensmile/src/core/configManager.cpp: In member function ‘void cConfigFileBuffer::loadFile(const char*, FILE*)’:
/data/home/opensmile/src/core/configManager.cpp:1722:6: error: use of deleted function ‘std::basic_ifstream<char>& std::basic_ifstream<char>::operator=(const std::basic_ifstream<char>&)’
   is = std::ifstream(filename, std::ifstream::in);   
      ^
In file included from /data/home/opensmile/src/include/core/configManager.hpp:27:0,
                 from /data/home/opensmile/src/core/configManager.cpp:30:
/usr/include/c++/4.8.2/fstream:427:11: note: ‘std::basic_ifstream<char>& std::basic_ifstream<char>::operator=(const std::basic_ifstream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_ifstream : public basic_istream<_CharT, _Traits>
           ^
/usr/include/c++/4.8.2/fstream:427:11: error: use of deleted function ‘std::basic_istream<char>& std::basic_istream<char>::operator=(const std::basic_istream<char>&)’
In file included from /usr/include/c++/4.8.2/iterator:65:0,
                 from /data/home/opensmile/src/include/rapidjson/document.h:56,
                 from /data/home/opensmile/src/include/core/configManager.hpp:22,
                 from /data/home/opensmile/src/core/configManager.cpp:30:
/usr/include/c++/4.8.2/istream:58:11: note: ‘std::basic_istream<char>& std::basic_istream<char>::operator=(const std::basic_istream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_istream : virtual public basic_ios<_CharT, _Traits>
           ^
/usr/include/c++/4.8.2/istream:58:11: error: use of deleted function ‘std::basic_ios<char>& std::basic_ios<char>::operator=(const std::basic_ios<char>&)’
In file included from /usr/include/c++/4.8.2/ios:44:0,
                 from /usr/include/c++/4.8.2/ostream:38,
                 from /usr/include/c++/4.8.2/iterator:64,
                 from /data/home/opensmile/src/include/rapidjson/document.h:56,
                 from /data/home/opensmile/src/include/core/configManager.hpp:22,
                 from /data/home/opensmile/src/core/configManager.cpp:30:
/usr/include/c++/4.8.2/bits/basic_ios.h:66:11: note: ‘std::basic_ios<char>& std::basic_ios<char>::operator=(const std::basic_ios<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_ios : public ios_base
           ^
In file included from /usr/include/c++/4.8.2/ios:42:0,
                 from /usr/include/c++/4.8.2/ostream:38,
                 from /usr/include/c++/4.8.2/iterator:64,
                 from /data/home/opensmile/src/include/rapidjson/document.h:56,
                 from /data/home/opensmile/src/include/core/configManager.hpp:22,
                 from /data/home/opensmile/src/core/configManager.cpp:30:
/usr/include/c++/4.8.2/bits/ios_base.h:789:5: error: ‘std::ios_base& std::ios_base::operator=(const std::ios_base&)’ is private
     operator=(const ios_base&);
     ^
In file included from /usr/include/c++/4.8.2/ios:44:0,
                 from /usr/include/c++/4.8.2/ostream:38,
                 from /usr/include/c++/4.8.2/iterator:64,
                 from /data/home/opensmile/src/include/rapidjson/document.h:56,
                 from /data/home/opensmile/src/include/core/configManager.hpp:22,
                 from /data/home/opensmile/src/core/configManager.cpp:30:
/usr/include/c++/4.8.2/bits/basic_ios.h:66:11: error: within this context
     class basic_ios : public ios_base
           ^
In file included from /data/home/opensmile/src/include/core/configManager.hpp:27:0,
                 from /data/home/opensmile/src/core/configManager.cpp:30:
/usr/include/c++/4.8.2/fstream:427:11: error: use of deleted function ‘std::basic_filebuf<char>& std::basic_filebuf<char>::operator=(const std::basic_filebuf<char>&)’
     class basic_ifstream : public basic_istream<_CharT, _Traits>
           ^
/usr/include/c++/4.8.2/fstream:72:11: note: ‘std::basic_filebuf<char>& std::basic_filebuf<char>::operator=(const std::basic_filebuf<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_filebuf : public basic_streambuf<_CharT, _Traits>
           ^
In file included from /usr/include/c++/4.8.2/ios:43:0,
                 from /usr/include/c++/4.8.2/ostream:38,
                 from /usr/include/c++/4.8.2/iterator:64,
                 from /data/home/opensmile/src/include/rapidjson/document.h:56,
                 from /data/home/opensmile/src/include/core/configManager.hpp:22,
                 from /data/home/opensmile/src/core/configManager.cpp:30:
/usr/include/c++/4.8.2/streambuf:810:7: error: ‘std::basic_streambuf<_CharT, _Traits>& std::basic_streambuf<_CharT, _Traits>::operator=(const std::basic_streambuf<_CharT, _Traits>&) [with _CharT = char; _Traits = std::char_traits<char>]’ is private
       operator=(const basic_streambuf& __sb)
       ^
In file included from /data/home/opensmile/src/include/core/configManager.hpp:27:0,
                 from /data/home/opensmile/src/core/configManager.cpp:30:
/usr/include/c++/4.8.2/fstream:72:11: error: within this context
     class basic_filebuf : public basic_streambuf<_CharT, _Traits>
           ^
[ 22%] Building CXX object CMakeFiles/opensmile.dir/src/core/dataReader.cpp.o
gmake[2]: *** [CMakeFiles/opensmile.dir/src/core/configManager.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/opensmile.dir/all] Error 2
gmake: *** [all] Error 2

**Comment by chausner-audeering** [comment]
The gcc version you are using is too old. You need one that supports at least C++11.

**Comment by srdfjy** [comment]
@chausner-audeering thanks

Recompiling, I solved it.
