### ISSUE TITLE
Output format

### ISSUE THREAD

**Issue by spagliarini** [audeering/opensmile#28]
Hi,

In the "Get started" page I read this:

> The output file format is the HTK parameter file format. For other file formats you must change the ‘cHtkSink’ component type in the configuration file to the type you want.

Which are the output format among I can choose? Is this valid for all the features, or only for plp? I am interested in mfcc and paraling, I 'd like to have a different format of output since I am having issues in reading .arff and .htk in python (or if you have experience with handling this type of files on any among Matlab, Python and R, any suggestion is accepted). 

Thank you in advance for the availability.
Silvia

**Comment by chausner-audeering** [comment]
It depends on which config file you use. Most of the config files include [config/shared/standard_data_output.conf.inc](https://github.com/audeering/opensmile/blob/master/config/shared/standard_data_output.conf.inc). for configuring outputs. It allows you to output features either in ARFF, HTK or CSV format. You can switch between the formats by changing the command-line option, e.g. `-output` for ARFF, `-htkoutput` for HTK, `-csvoutput` for CSV.

**Comment by chausner-audeering** [comment]
I hope your question has been answered, thus I'll close this issue. Feel free to reopen if you have further questions on output formats.
