### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by guiandrade2** [audeering/opensmile#3]
I am having trouble installing opensmile on windows. I dont know exactly what I have to do or where do I have to type the commands specified. could you be a bit more specific on instructions?

**Comment by chausner-audeering** [comment]
It's easiest if you use the pre-compiled binaries from https://github.com/audeering/opensmile/releases/download/v3.0.0/opensmile-3.0-win-x64.zip. Just extract the ZIP file to an arbitrary location and you can start using `SMILExtract.exe` as outlined in the [documentation](https://audeering.github.io/opensmile/get-started.html#extracting-your-first-features).

**Comment by drux007** [comment]
@guiandrade2, did the instructions that @chausner-audeering wrote you in [post](https://github.com/audeering/opensmile/issues/3#issuecomment-759402081) help you?

Can we close the issue?

**Comment by BotMichael** [comment]
does the pre-compiled binary capable of extracting video features?

**Comment by chausner-audeering** [comment]
> does the pre-compiled binary capable of extracting video features?

The pre-compiled binary releases have not been compiled with OpenCV support. Please see Sections [Compiling on Linux/Mac with PortAudio and OpenCV support](https://audeering.github.io/opensmile/get-started.html#compiling-on-linux-mac-with-portaudio-and-opencv-support) and [Compiling on Windows with PortAudio and OpenCV support](https://audeering.github.io/opensmile/get-started.html#compiling-on-windows-with-portaudio-and-opencv-support) in the documentation for how to compile with OpenCV.

Note that openSMILE has only very limited video feature extraction support and its compatibility has not been tested with newer OpenCV versions.

**Comment by guiandrade2** [comment]
@chausner-audeering @drux007  I need to compile it with PortAudio support, so I am guessing the pre compiled binaries won't do it, I cloned the repository, then followed the steps from the documentation using vcpkg to install portAudio, changed the build config at build_flags.ps1 to use portaudio, but at running the command on the VS 2019 powershell, I still get an error on missing portaudio.h file.

**Comment by guiandrade2** [comment]
@drux007 @chausner-audeering I needed to compile with PortAudio support, I managed to figure it out by checking out the links you sent me and exploring a bit, had a few issues with vcpkg but all done, thank you for the help and sorry for my delayed reply.

**Comment by drux007** [comment]
Great that you managed to solve it by looking at the documentation!
