### ISSUE TITLE
eGeMAPS V01b and GeMAPS V01b

### ISSUE THREAD

**Issue by Ali-Darzi** [audeering/opensmile#30]
I am running OpenSmile 3.0.0 on two machines (Mac and Windows) to get GeMAPS features V01b. In both cases, I get the calculated features for the first frame only in the CSV file, and the following warning: 

(WRN) [2] cComponentManager: The following component(s) could not perform any work because destination levels are full but no other component performed any work either: lldconcat. Processing will possibly be incomplete. For more details, enable the execDebug option of cComponentManager.

What could the be the problem and how can I fix it?

**Comment by Ali-Darzi** [comment]
You guessed right and it fixed my problem. Thanks.

**Comment by chausner-audeering** [comment]
Great! I'll close this issue then.
