### ISSUE TITLE
Executable SMILExtract.exe doesn't work

### ISSUE THREAD

**Issue by FilipWichrowski** [audeering/opensmile#33]
Hi,
I tried both installing the newest release version of openSMILE and building it from scratch, but whenever I try to launch SMILExtract.exe there just pops out an empty command prompt (for just a blink of an eye) and that's all. I tried on four different PC's (Win10/Win11) with exactly the same result. Has anyone got the idea what might be wrong?
Filip

**Comment by chausner-audeering** [comment]
That is to be expected since openSMILE is a command-line program. You need to start it from within the command-line to see its output.

**Comment by chausner-audeering** [comment]
I'll close this issue since the behavior you report is expected. Feel free to reopen if you feel your question was not fully answered yet.
