### ISSUE TITLE
use of undeclared identifier 'finite' error 

### ISSUE THREAD

**Issue by tiedurden** [audeering/opensmile#40]
Following 4 files are affected: 
VektorMVN.cpp
libsvmSink.cpp 
functionallRegression.cpp
functionalDCT.cpp

after changing it locally to isinfite the installation could be finished withoud errors

**Comment by chausner-audeering** [comment]
Thanks for reporting this issue. We should have a new release in January which will include a fix for this. Until then, I'll leave this issue open.
