### ISSUE TITLE
Execution failed for task ':opensmile:compileDebugKotlin'. > Compilation error. See log for more details(Android_template))

### ISSUE THREAD

**Issue by tridtay** [audeering/opensmile#41]
java 11
swig 4.0.1
ubuntu 20

i execute this line
./gradlew app:assembleUseSource

error message: [Execution failed for task ':opensmile:compileDebugKotlin'. > Compilation error. See log for more details]
i have idea to edit AndroidManifest.xml
guide pls.

error log:
[manifest-merger-debug-report.txt](https://github.com/audeering/opensmile/files/7774607/manifest-merger-debug-report.txt)

AndroidManifest.xml file:

`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.audeering.opensmile" />`

**Comment by chausner-audeering** [comment]
There should be another build log with more information about the compilation error.
