### ISSUE TITLE
Correct field in output .wav file header

### ISSUE THREAD

**Issue by ceqq** [audeering/opensmile#42]
For 32-bit float PCM WAV, AudioFormat (Compression type) field must contain 3 (IEEE float).
Correct 2 files (waveSink.cpp, waveSinkCut.cpp):
  head.AudioFormat = sampleFormat == SMILE_SF_32BIT_FLOAT ? 3 : 1; // !!! ??
Otherwise the float wav files are misinterpreted by a number of programs.
https://audiocoding.ru/articles/2008-05-22-wav-file-structure/wav_formats.txt
Best regards
Yevgueny

**Comment by chausner-audeering** [comment]
Thanks a lot for reporting this bug! I've fixed this in our internal version and we have planned to make a new open-source GitHub release in January which will include this fix and other improvements. Until then, I'll leave this issue open for now.

**Comment by ceqq** [comment]
Great! And nice to meet you. I've corrected it for myself in the local version, which is quite enough for me. Will report if find more. (I'm trying using it for 1-st day only, and with the current documentation it's necessary to read certain sources and test edge cases in detail.)

**Comment by chausner-audeering** [comment]
Version 3.0.1 has been released with a fix so I'll close this issue.
