### ISSUE TITLE
libm.so.6: version 'GLIBC_2.27' not found

### ISSUE THREAD

**Issue by oscarliii** [audeering/opensmile#47]
Hi, when I import opensmile in python, it gives this error: /lib64/libm.so.6: version `GLIBC_2.27' not found.
My machine is: ldd (Ubuntu GLIBC 2.31-0ubuntu9.7) 2.31.
It seems opensmile does not support new GLIBC version?

**Comment by chausner-audeering** [comment]
Which exact Ubuntu version are you using? Normally, operating systems include older GLIBC versions for backwards-compatibility. The pre-built binaries that we provide have been built using GLIBC 2.27.

As a workaround, you could manually build openSMILE on your machine.

**Comment by oscarliii** [comment]
Thanks for the quick reply.
_Which exact Ubuntu version are you using?_
I'm using Ubuntu 20.04.4 LTS.
_>>you could manually build openSMILE on your machineI_
I don't have permission as the machine is administrated by the remote host.
Am I stuck at this point?

**Comment by chausner-audeering** [comment]
Ubuntu 20.04 should be supported, I am using the exact same version.
```
$ ldd bin/SMILExtract 
	linux-vdso.so.1 (0x00007ffd4abd4000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f9b4234d000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9b421fe000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f9b421e3000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f9b421c0000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9b41fce000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f9b4271a000)
```

Interesting that on your machine, it tries to load `/lib64/libm.so.6` instead of `/lib/x86_64-linux-gnu/libm.so.6`. `/lib64/libm.so.6` does not exist on my system.

**Comment by chausner-audeering** [comment]
Can you try invoking it like this:
```bash
LD_LIBRARY_PATH=/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH bin/SMILExtract
```

**Comment by oscarliii** [comment]
bin/SMILExtract: No such file or directory.
Can I solve the problem with conda's virtual environment?

**Comment by chausner-audeering** [comment]
> bin/SMILExtract: No such file or directory.

Please download the standalone version of openSMILE from the GitHub releases page and try to run the above command.

**Comment by oscarliii** [comment]
Thanks. It works!
