### ISSUE TITLE
(MSG):  No filename given

### ISSUE THREAD

**Issue by op-Valar-Morghulis** [audeering/opensmile#48]
![image](https://user-images.githubusercontent.com/37147039/171033180-9bd11d0e-6d51-4ef6-a1e6-660ddb1b971a.png)
Thanks for your amazing software. 
I have encounter some messages when I was using opensmile to extact the feature of .wav file.
I wondered what is the problem with my usage.
Could you give me some advice on it ?
The command I used looks like this:
`
cd /content/drive/MyDrive/opensmile && ./SMILExtract -C /content/drive/MyDrive/opensmile/config/is09-13/IS09_emotion.conf -I /content/drive/MyDrive/audio_0.wav -O /content/drive/opensmile_extract/audio_0.txt
`

**Comment by chausner-audeering** [comment]
You can ignore those messages, they are normal and expected. They just say that some of the outputs (functionals in CSV and HTK format and all LLDs) are disabled because you did not specify output paths for them on the command-line.

**Comment by op-Valar-Morghulis** [comment]
> You can ignore those messages, they are normal and expected. They just say that some of the outputs (functionals in CSV and HTK format and all LLDs) are disabled because you did not specify output paths for them on the command-line.

Thanks for your reply. So do those outputs affect the output features of .wav file ?

**Comment by chausner-audeering** [comment]
No, they do not affect the features. There are just different formats that the features can be output in (ARFF, CSV, HTK). You are using `-O` which outputs in the ARFF format.
