### ISSUE TITLE
build error no such file src/include/io/rosSink.hpp:55:10: fatal error: ros/ros.h:

### ISSUE THREAD

**Issue by cuiyimeng** [audeering/opensmile#55]
I get an error output after executing the make command

src/include/io/rosSink.hpp:55:10: fatal error: ros/ros.h: No such file or directory
 #include <ros/ros.h>
          ^~~~~~~~~~~
compilation terminated.
Makefile:1480: recipe for target 'src/core/libopensmile_la-componentManager.lo' failed
make[1]: *** [src/core/libopensmile_la-componentManager.lo] Error 1
make[1]: Leave directory “/home/ubuntu/program/opensmile-2.3.0”
Makefile:660: recipe for target 'all' failed
make: *** [all] Error 2

os:ubuntu 18.04
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)

**Comment by chausner-audeering** [comment]
It appears you are trying to build a non-official fork of openSMILE, see https://github.com/georgepar/opensmile. `src/include/io/rosSink.hpp` is not part of openSMILE.

**Comment by cuiyimeng** [comment]
thanks
