### ISSUE TITLE
Execution failed for task ':opensmile:generateJsonModelDebug'.

### ISSUE THREAD

**Issue by Iesus90** [audeering/opensmile#6]
> Task :opensmile:generateJsonModelDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':opensmile:generateJsonModelDebug'.
> C:\Users\...\Desktop\opensmile\progsrc\android-template\opensmile\CMakeLists.txt : C/C++ debug|armeabi-v7a : CMake Error: File C:/Users/.../Desktop/opensmile/progsrc/android-template/
opensmile/src/include/core/git_version.hpp.in does not exist.

Can someone help me ?

**Comment by chausner-audeering** [comment]
Can you please post the exact command you use to compile the Android sample?

@hesamsagha Any idea why that file is missing?

**Comment by hesamsagha** [comment]
could you comment out references (includes) to the git_version.* in the codes?

**Comment by hagenw** [comment]
> could you comment out references (includes) to the git_version.* in the codes?

Is this the considered way of building it, or should we maybe fix the code by removing `git_version.*` or adding the missing file?

**Comment by Iesus90** [comment]
I was able to solve this problem.

**Comment by Iesus90** [comment]
Now I have this error: Run command gradlew opensmile:assemble

clang++: warning: argument unused during compilation: '-fuse-ld=gold' [-Wunused-command-line-argument]
  ../../../../src/smileapi/SMILEapi.cpp:14:10: fatal error: 'smileapi/SMILEapi.h' file not found
  #include <smileapi/SMILEapi.h>
           ^~~~~~~~~~~~~~~~~~~~~
  1 error generated.
  [154/157] Building CXX object src/smilextract/CMakeFiles/SMILExtract.dir/SMILExtract.cpp.o
  clang++: warning: argument unused during compilation: '-fuse-ld=gold' [-Wunused-command-line-argument]
  [155/157] Linking CXX shared library ..\..\..\..\build\intermediates\cmake\debug\obj\armeabi-v7a\libopensmile.so
  ninja: build stopped: subcommand failed.

**Comment by Iesus90** [comment]
Ok. All Right
