### ISSUE TITLE
Fail to get file list com.audeering.androidtemplate

### ISSUE THREAD

**Issue by Iesus90** [audeering/opensmile#7]
getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array

When I click Test Opensles or any other audio recording button, the application closes and Logcat appears these errors.

**Comment by chausner-audeering** [comment]
@hesamsagha Could you please jump in once again? :)

**Comment by hesamsagha** [comment]
Have you given permission to the app to read/write to file?
What android version/mobile phone you are using?
Please also copy the full stacktrace

**Comment by Iesus90** [comment]
I can resolve !!

**Comment by hesamsagha** [comment]
@Iesus90 could you let me know what the source of problem was? and how you resolved it?

**Comment by Iesus90** [comment]
I updated the NDK version to 21.0.6113669
